### ISSUE TITLE
getGridAudiogram function

### ISSUE THREAD

**Issue by bjacquot** [cambridge-mlg/BALaudiogram#1]
Hi,

when i try to run your program, after some sounds sample i got an error :
Unrecognized function or variable 'getGridAudiogram'.
Error in getNextAudiogramTrialGP (line 17)
[x,y,t, tforig, tLorig] = getGridAudiogram( vFPresented, vLPresented, vAnswers, nMinF, nMaxF, dStepSize, LgridMin, LgridMax );

Where can i find this function ?

**Comment by yonefx** [comment]
There might be an error in a code restructuring process. The initial version (#commit 4ca704a761c654db39d69f2742bb7de791660992) works fine.

**Comment by js2251** [comment]
Thank you for reporting the problem, sorry for fixing it so late. It works now.
The initial version (or version 2 from the same day) was tested extensively.
The current version is more beautiful and should be used if you are interested in the code.
